create table city(
id BIGINT generated by default as identity(start with 1 INCREMENT BY 1),
name varchar(20),
created_date timestamp,
updated_date timestamp,
primary key(id))

create table state(
id BIGINT generated by default as identity(start with 1 INCREMENT BY 1),
name varchar(20),
created_date timestamp,
updated_date timestamp,
primary key(id))

create table address_type(
id BIGINT generated by default as identity(start with 1 INCREMENT BY 1),
name varchar(20),
created_date timestamp,
updated_date timestamp,
primary key(id))

create table contact(
id BIGINT generated by default as identity(start with 1 INCREMENT BY 1),
name varchar(25),
email_address varchar(15),
dob date,
anniversary date,
created_date timestamp,
updated_date timestamp,
primary key(id))

create table address(
id BIGINT generated by default as identity(start with 1 INCREMENT BY 1),
addrLine1 text,
addrLine2 text,
addrLine3 text,
city_id bigint unique not null,
state_id bigint unique not null,
address_type_id bigint unique not null,
contact_id bigint unique not null,
created_date timestamp,
updated_date timestamp,
position INT,
primary key(id),
foreign key(city_id) references city(id),
foreign key(state_id) references state(id),
foreign key(address_type_id) references address_type(id),
foreign key(contact_id) references contact(id))

create table system_config(
id BIGINT generated by default as identity(start with 1 INCREMENT BY 1),
key text,
value text,
primary key(id))

insert into system_config(key,value) values('api.layer.log.level','info');
insert into system_config(key,value) values('other.layer.log.level','debug');
